spring.application.name=Proyecto

spring.datasource.url=jdbc:postgresql://localhost:5432/db_restauranteavenida
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Juanma2406
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracion de Hibernate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.Type=TRACE
logging.level.org.springframework.security=DEBUG

# Permite el acceso a recursos estaticos
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

#JWT
jwt.secret=secret
jwt.expiration=3600
jwt.accessTokenCookieName=AuthToken

spring.messages.encoding=UTF-8

server.port=8080
server.ssl.enabled=false

app.upload.dir=uploads/images